# Generated by Django 4.2 on 2023-04-20 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="developer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
